# AWS Profile Configuration
variable "aws_profile" {
  description = "AWS CLI profile to use for authentication"
  type        = string
  default     = "default"
}

# Region configuration
variable "aws_region" {
  description = "AWS region where resources will be created"
  type        = string
  default     = "us-east-1"
}

variable "vpc_name" {
  description = "Name prefix for VPC and related resources"
  type        = string
}

variable "environment" {
  description = "Environment name (dev, demo, prod)"
  type        = string
  default     = "dev"
}

# VPC CIDR block
variable "vpc_cidr" {
  description = "CIDR block for VPC"
  type        = string
  default     = "10.0.0.0/16"

  validation {
    condition     = can(cidrhost(var.vpc_cidr, 0))
    error_message = "VPC CIDR must be a valid IPv4 CIDR block"
  }
}

# Availability Zone configuration
variable "availability_zones" {
  description = "List of specific availability zones to use (leave empty to use all available)"
  type        = list(string)
  default     = []
}

variable "az_count" {
  description = "Number of availability zones to use (only used if availability_zones is empty)"
  type        = number
  default     = 3

  validation {
    condition     = var.az_count >= 1 && var.az_count <= 10
    error_message = "AZ count must be between 1 and 10"
  }
}

# Subnet configuration
variable "public_subnet_count" {
  description = "Number of public subnets to create"
  type        = number
  default     = 3

  validation {
    condition     = var.public_subnet_count >= 1 && var.public_subnet_count <= 20
    error_message = "Public subnet count must be between 1 and 20"
  }
}

variable "private_subnet_count" {
  description = "Number of private subnets to create"
  type        = number
  default     = 3

  validation {
    condition     = var.private_subnet_count >= 1 && var.private_subnet_count <= 20
    error_message = "Private subnet count must be between 1 and 20"
  }
}

# Subnet CIDR sizing
variable "subnet_cidr_newbits" {
  description = "Number of bits to add to VPC CIDR for subnets (8 = /24 subnets from /16 VPC)"
  type        = number
  default     = 8

  validation {
    condition     = var.subnet_cidr_newbits >= 4 && var.subnet_cidr_newbits <= 16
    error_message = "Subnet newbits must be between 4 and 16"
  }
}

# Enable/disable DNS settings
variable "enable_dns_hostnames" {
  description = "Enable DNS hostnames in the VPC"
  type        = bool
  default     = true
}

variable "enable_dns_support" {
  description = "Enable DNS support in the VPC"
  type        = bool
  default     = true
}

# Security Group Configuration
variable "application_port" {
  description = "Port on which the application runs"
  type        = number
  default     = 8000

  validation {
    condition     = var.application_port >= 1 && var.application_port <= 65535
    error_message = "Application port must be between 1 and 65535"
  }
}

# EC2 Instance Configuration
variable "ec2_key_name" {
  description = "Name of the EC2 key pair for SSH access"
  type        = string
}

variable "instance_type" {
  description = "EC2 instance type"
  type        = string
  default     = "t2.micro"
}

variable "root_volume_size" {
  description = "Size of root EBS volume in GB"
  type        = number
  default     = 25

  validation {
    condition     = var.root_volume_size >= 8 && var.root_volume_size <= 16384
    error_message = "Root volume size must be between 8 GB and 16 TB"
  }
}

variable "root_volume_type" {
  description = "Type of root EBS volume"
  type        = string
  default     = "gp2"

  validation {
    condition     = contains(["gp2", "gp3", "io1", "io2", "st1", "sc1"], var.root_volume_type)
    error_message = "Root volume type must be one of: gp2, gp3, io1, io2, st1, sc1"
  }
}

# AMI Configuration
variable "custom_ami_id" {
  description = "Custom AMI ID to use for EC2 instance (leave empty to use latest)"
  type        = string
  default     = ""
}

variable "ami_owner_id" {
  description = "AWS account ID that owns the AMI"
  type        = string
}

variable "ami_name_filter" {
  description = "Name filter pattern for AMI search"
  type        = string
  default     = "csye6225-*"
}

# Common Tags
variable "common_tags" {
  description = "Common tags to apply to all resources"
  type        = map(string)
  default     = {}
}

# Database Configuration
variable "db_name" {
  description = "Database name"
  type        = string
  default     = "csye6225"
}

variable "db_username" {
  description = "Database master username"
  type        = string
  default     = "csye6225"
}

# ✅ PASSWORD IS NOW OPTIONAL - Auto-generated by random_password resource
variable "db_password" {
  description = "Database master password (optional - will be auto-generated if not provided)"
  type        = string
  sensitive   = true
  default     = null # Will be auto-generated if null
}

# ============================================================================
# RDS CONFIGURATION VARIABLES
# ============================================================================

# Database Engine Configuration
variable "db_engine_version" {
  description = "PostgreSQL engine version"
  type        = string
  default     = "16.4"
}

variable "db_instance_class" {
  description = "RDS instance class"
  type        = string
  default     = "db.t3.micro"

  validation {
    condition     = can(regex("^db\\.", var.db_instance_class))
    error_message = "Instance class must start with 'db.'"
  }
}

# Storage Configuration
variable "db_allocated_storage" {
  description = "Initial storage allocation in GB"
  type        = number
  default     = 20

  validation {
    condition     = var.db_allocated_storage >= 20 && var.db_allocated_storage <= 65536
    error_message = "Allocated storage must be between 20 GB and 64 TB"
  }
}

variable "db_max_allocated_storage" {
  description = "Maximum storage for autoscaling in GB (0 to disable)"
  type        = number
  default     = 100
}

variable "db_storage_type" {
  description = "Storage type (gp2, gp3, io1)"
  type        = string
  default     = "gp3"

  validation {
    condition     = contains(["gp2", "gp3", "io1"], var.db_storage_type)
    error_message = "Storage type must be gp2, gp3, or io1"
  }
}

# High Availability Configuration
variable "db_multi_az" {
  description = "Enable Multi-AZ deployment"
  type        = bool
  default     = false # Set to true for production
}

# Backup Configuration
variable "db_backup_retention_period" {
  description = "Number of days to retain backups (0-35)"
  type        = number
  default     = 7

  validation {
    condition     = var.db_backup_retention_period >= 0 && var.db_backup_retention_period <= 35
    error_message = "Backup retention must be between 0 and 35 days"
  }
}

variable "db_backup_window" {
  description = "Preferred backup window (UTC)"
  type        = string
  default     = "03:00-04:00"
}

variable "db_maintenance_window" {
  description = "Preferred maintenance window (UTC)"
  type        = string
  default     = "sun:04:00-sun:05:00"
}

# Deletion Protection
variable "db_deletion_protection" {
  description = "Enable deletion protection"
  type        = bool
  default     = false # Set to true for production
}

# ========================================
# Auto Scaling Group Variables
# ========================================

variable "asg_min_size" {
  description = "Minimum number of instances in ASG"
  type        = number
  default     = 3
}

variable "asg_max_size" {
  description = "Maximum number of instances in ASG"
  type        = number
  default     = 5
}

variable "asg_desired_capacity" {
  description = "Desired number of instances in ASG"
  type        = number
  default     = 1
}

variable "asg_cooldown" {
  description = "Cooldown period in seconds between scaling activities"
  type        = number
  default     = 60
}

variable "asg_health_check_grace_period" {
  description = "Time in seconds after instance comes into service before checking health"
  type        = number
  default     = 300
}

# ========================================
# Application Load Balancer Variables
# ========================================

variable "alb_name" {
  description = "Name of the Application Load Balancer"
  type        = string
  default     = "csye6225-alb"
}

variable "health_check_path" {
  description = "Health check endpoint path"
  type        = string
  default     = "/healthz"
}

variable "health_check_interval" {
  description = "Health check interval in seconds"
  type        = number
  default     = 30
}

variable "health_check_timeout" {
  description = "Health check timeout in seconds"
  type        = number
  default     = 5
}

variable "healthy_threshold" {
  description = "Number of consecutive health checks successes required"
  type        = number
  default     = 2
}

variable "unhealthy_threshold" {
  description = "Number of consecutive health check failures required"
  type        = number
  default     = 2
}

# variable "application_port" {
#   description = "Port on which the application runs"
#   type        = number
#   default     = 8000
# }

# ========================================
# Auto Scaling Policy Variables
# ========================================

variable "scale_up_cpu_threshold" {
  description = "CPU percentage threshold to trigger scale up"
  type        = number
  default     = 5.0
}

variable "scale_down_cpu_threshold" {
  description = "CPU percentage threshold to trigger scale down"
  type        = number
  default     = 3.0
}

variable "scale_up_adjustment" {
  description = "Number of instances to add during scale up"
  type        = number
  default     = 1
}

variable "scale_down_adjustment" {
  description = "Number of instances to remove during scale down"
  type        = number
  default     = -1
}

# ========================================
# DNS Variables
# ========================================

variable "domain_name" {
  description = "Root domain name"
  type        = string
}

variable "subdomain" {
  description = "Subdomain prefix (dev, demo, or empty for root)"
  type        = string
}

variable "route53_zone_id" {
  description = "Route53 hosted zone ID"
  type        = string
}

# ========================================
# SendGrid Configuration (Assignment 9)
# ========================================

variable "sendgrid_api_key" {
  description = "SendGrid API key for email notifications"
  type        = string
  sensitive   = true

  validation {
    condition     = can(regex("^SG\\.", var.sendgrid_api_key))
    error_message = "SendGrid API key must start with 'SG.'"
  }
}